import Navbar from '@/components/Navbar'
import 'bootstrap/dist/css/bootstrap.css';
import '@/styles/globals.css'
import Navbottom from '@/components/Navbottom';
import Footer from '@/components/Footer';
import Head from 'next/head';

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>pk</title>
        <meta name='description' content='generated by create next app' />
        <meta name='viewport' content='width=device-width , initial-scale=1' />
        <link rel="icon" href='/GT.png' />
      </Head>
      < Navbar />
      <Navbottom />
      <Component {...pageProps} />
      <Footer />
    </>

  )
}
